# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Auto re-deploy site
on:
  schedule:
    - cron: '0 7 * * SUN'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel deploy url
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_PiOR40ZdB6INhAMNaWlXBaxrd274/QGVD6jeOal
